/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.ncl.ui.AbstractNCLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class NCLUiModule extends AbstractNCLUiModule {
  public NCLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
