/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.ui.contentassist;

import org.xtext.example.ncl.ui.contentassist.AbstractNCLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class NCLProposalProvider extends AbstractNCLProposalProvider {
}
