/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.ncl.parser.antlr.internal.InternalNCLParser;
import org.xtext.example.ncl.services.NCLGrammarAccess;

public class NCLParser extends AbstractAntlrParser {

	@Inject
	private NCLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalNCLParser createParser(XtextTokenStream stream) {
		return new InternalNCLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TopLevelCP";
	}

	public NCLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(NCLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
