/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.ide;

import org.xtext.example.ncl.ide.AbstractNCLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class NCLIdeModule extends AbstractNCLIdeModule {
}
