/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.ncl.NCLRuntimeModule;
import org.xtext.example.ncl.NCLStandaloneSetup;
import org.xtext.example.ncl.ide.NCLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class NCLIdeSetup extends NCLStandaloneSetup {
  @Override
  public Injector createInjector() {
    NCLRuntimeModule _nCLRuntimeModule = new NCLRuntimeModule();
    NCLIdeModule _nCLIdeModule = new NCLIdeModule();
    return Guice.createInjector(Modules2.mixin(_nCLRuntimeModule, _nCLIdeModule));
  }
}
