/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.nCL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.ncl.nCL.HeteStatementCS;
import org.xtext.example.ncl.nCL.HetecomCP;
import org.xtext.example.ncl.nCL.NCLPackage;
import org.xtext.example.ncl.nCL.metaModelTypeCS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hetecom CP</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ncl.nCL.impl.HetecomCPImpl#getOwnedModels <em>Owned Models</em>}</li>
 *   <li>{@link org.xtext.example.ncl.nCL.impl.HetecomCPImpl#getOwnedStatements <em>Owned Statements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HetecomCPImpl extends MinimalEObjectImpl.Container implements HetecomCP
{
  /**
   * The cached value of the '{@link #getOwnedModels() <em>Owned Models</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedModels()
   * @generated
   * @ordered
   */
  protected EList<metaModelTypeCS> ownedModels;

  /**
   * The cached value of the '{@link #getOwnedStatements() <em>Owned Statements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOwnedStatements()
   * @generated
   * @ordered
   */
  protected EList<HeteStatementCS> ownedStatements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HetecomCPImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NCLPackage.Literals.HETECOM_CP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<metaModelTypeCS> getOwnedModels()
  {
    if (ownedModels == null)
    {
      ownedModels = new EObjectContainmentEList<metaModelTypeCS>(metaModelTypeCS.class, this, NCLPackage.HETECOM_CP__OWNED_MODELS);
    }
    return ownedModels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<HeteStatementCS> getOwnedStatements()
  {
    if (ownedStatements == null)
    {
      ownedStatements = new EObjectContainmentEList<HeteStatementCS>(HeteStatementCS.class, this, NCLPackage.HETECOM_CP__OWNED_STATEMENTS);
    }
    return ownedStatements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case NCLPackage.HETECOM_CP__OWNED_MODELS:
        return ((InternalEList<?>)getOwnedModels()).basicRemove(otherEnd, msgs);
      case NCLPackage.HETECOM_CP__OWNED_STATEMENTS:
        return ((InternalEList<?>)getOwnedStatements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case NCLPackage.HETECOM_CP__OWNED_MODELS:
        return getOwnedModels();
      case NCLPackage.HETECOM_CP__OWNED_STATEMENTS:
        return getOwnedStatements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case NCLPackage.HETECOM_CP__OWNED_MODELS:
        getOwnedModels().clear();
        getOwnedModels().addAll((Collection<? extends metaModelTypeCS>)newValue);
        return;
      case NCLPackage.HETECOM_CP__OWNED_STATEMENTS:
        getOwnedStatements().clear();
        getOwnedStatements().addAll((Collection<? extends HeteStatementCS>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case NCLPackage.HETECOM_CP__OWNED_MODELS:
        getOwnedModels().clear();
        return;
      case NCLPackage.HETECOM_CP__OWNED_STATEMENTS:
        getOwnedStatements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case NCLPackage.HETECOM_CP__OWNED_MODELS:
        return ownedModels != null && !ownedModels.isEmpty();
      case NCLPackage.HETECOM_CP__OWNED_STATEMENTS:
        return ownedStatements != null && !ownedStatements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //HetecomCPImpl
