/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl;

import org.xtext.example.ncl.AbstractNCLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class NCLRuntimeModule extends AbstractNCLRuntimeModule {
}
