/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl;

import org.xtext.example.ncl.NCLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class NCLStandaloneSetup extends NCLStandaloneSetupGenerated {
  public static void doSetup() {
    new NCLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
