/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.ncl.ui.internal.NclActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NCLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(NclActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		NclActivator activator = NclActivator.getInstance();
		return activator != null ? activator.getInjector(NclActivator.ORG_XTEXT_EXAMPLE_NCL_NCL) : null;
	}

}
