/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NCLRuntimeModule extends AbstractNCLRuntimeModule {
}
