/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NCLStandaloneSetup extends NCLStandaloneSetupGenerated {

	def static void doSetup() {
		new NCLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
