/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.nCL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hetecom CP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ncl.nCL.HetecomCP#getOwnedModels <em>Owned Models</em>}</li>
 *   <li>{@link org.xtext.example.ncl.nCL.HetecomCP#getOwnedStatements <em>Owned Statements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ncl.nCL.NCLPackage#getHetecomCP()
 * @model
 * @generated
 */
public interface HetecomCP extends EObject
{
  /**
   * Returns the value of the '<em><b>Owned Models</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ncl.nCL.metaModelTypeCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Models</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Models</em>' containment reference list.
   * @see org.xtext.example.ncl.nCL.NCLPackage#getHetecomCP_OwnedModels()
   * @model containment="true"
   * @generated
   */
  EList<metaModelTypeCS> getOwnedModels();

  /**
   * Returns the value of the '<em><b>Owned Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ncl.nCL.HeteStatementCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Statements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Statements</em>' containment reference list.
   * @see org.xtext.example.ncl.nCL.NCLPackage#getHetecomCP_OwnedStatements()
   * @model containment="true"
   * @generated
   */
  EList<HeteStatementCS> getOwnedStatements();

} // HetecomCP
