/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.nCL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.ncl.nCL.NCLPackage
 * @generated
 */
public interface NCLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  NCLFactory eINSTANCE = org.xtext.example.ncl.nCL.impl.NCLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Top Level CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Top Level CP</em>'.
   * @generated
   */
  TopLevelCP createTopLevelCP();

  /**
   * Returns a new object of class '<em>Homocom CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Homocom CP</em>'.
   * @generated
   */
  HomocomCP createHomocomCP();

  /**
   * Returns a new object of class '<em>meta Model Type CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>meta Model Type CS</em>'.
   * @generated
   */
  metaModelTypeCS createmetaModelTypeCS();

  /**
   * Returns a new object of class '<em>Homo Statement CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Homo Statement CS</em>'.
   * @generated
   */
  HomoStatementCS createHomoStatementCS();

  /**
   * Returns a new object of class '<em>Homo Condition CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Homo Condition CS</em>'.
   * @generated
   */
  HomoConditionCS createHomoConditionCS();

  /**
   * Returns a new object of class '<em>Hetecom CP</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hetecom CP</em>'.
   * @generated
   */
  HetecomCP createHetecomCP();

  /**
   * Returns a new object of class '<em>Hete Statement CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hete Statement CS</em>'.
   * @generated
   */
  HeteStatementCS createHeteStatementCS();

  /**
   * Returns a new object of class '<em>Hete Condition CS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hete Condition CS</em>'.
   * @generated
   */
  HeteConditionCS createHeteConditionCS();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  NCLPackage getNCLPackage();

} //NCLFactory
