/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.nCL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.ncl.nCL.NCLFactory
 * @model kind="package"
 * @generated
 */
public interface NCLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "nCL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/ncl/NCL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "nCL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  NCLPackage eINSTANCE = org.xtext.example.ncl.nCL.impl.NCLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.ncl.nCL.impl.TopLevelCPImpl <em>Top Level CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ncl.nCL.impl.TopLevelCPImpl
   * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getTopLevelCP()
   * @generated
   */
  int TOP_LEVEL_CP = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__NAME = 0;

  /**
   * The feature id for the '<em><b>Owned Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_IMPORTS = 1;

  /**
   * The feature id for the '<em><b>Owned Homocoms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_HOMOCOMS = 2;

  /**
   * The feature id for the '<em><b>Owned Hetecoms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP__OWNED_HETECOMS = 3;

  /**
   * The number of structural features of the '<em>Top Level CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOP_LEVEL_CP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.ncl.nCL.impl.HomocomCPImpl <em>Homocom CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ncl.nCL.impl.HomocomCPImpl
   * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHomocomCP()
   * @generated
   */
  int HOMOCOM_CP = 1;

  /**
   * The feature id for the '<em><b>Owned Meta Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOMOCOM_CP__OWNED_META_MODELS = 0;

  /**
   * The feature id for the '<em><b>Owned Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOMOCOM_CP__OWNED_STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Homocom CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOMOCOM_CP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.ncl.nCL.impl.metaModelTypeCSImpl <em>meta Model Type CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ncl.nCL.impl.metaModelTypeCSImpl
   * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getmetaModelTypeCS()
   * @generated
   */
  int META_MODEL_TYPE_CS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_MODEL_TYPE_CS__NAME = 0;

  /**
   * The number of structural features of the '<em>meta Model Type CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int META_MODEL_TYPE_CS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.ncl.nCL.impl.HomoStatementCSImpl <em>Homo Statement CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ncl.nCL.impl.HomoStatementCSImpl
   * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHomoStatementCS()
   * @generated
   */
  int HOMO_STATEMENT_CS = 3;

  /**
   * The feature id for the '<em><b>Owned Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOMO_STATEMENT_CS__OWNED_CONDITIONS = 0;

  /**
   * The number of structural features of the '<em>Homo Statement CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOMO_STATEMENT_CS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.ncl.nCL.impl.HomoConditionCSImpl <em>Homo Condition CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ncl.nCL.impl.HomoConditionCSImpl
   * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHomoConditionCS()
   * @generated
   */
  int HOMO_CONDITION_CS = 4;

  /**
   * The feature id for the '<em><b>Owned Element A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOMO_CONDITION_CS__OWNED_ELEMENT_A = 0;

  /**
   * The feature id for the '<em><b>Owned Element B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOMO_CONDITION_CS__OWNED_ELEMENT_B = 1;

  /**
   * The feature id for the '<em><b>Owned Element</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOMO_CONDITION_CS__OWNED_ELEMENT = 2;

  /**
   * The number of structural features of the '<em>Homo Condition CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOMO_CONDITION_CS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.ncl.nCL.impl.HetecomCPImpl <em>Hetecom CP</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ncl.nCL.impl.HetecomCPImpl
   * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHetecomCP()
   * @generated
   */
  int HETECOM_CP = 5;

  /**
   * The feature id for the '<em><b>Owned Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HETECOM_CP__OWNED_MODELS = 0;

  /**
   * The feature id for the '<em><b>Owned Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HETECOM_CP__OWNED_STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Hetecom CP</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HETECOM_CP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.ncl.nCL.impl.HeteStatementCSImpl <em>Hete Statement CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ncl.nCL.impl.HeteStatementCSImpl
   * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHeteStatementCS()
   * @generated
   */
  int HETE_STATEMENT_CS = 6;

  /**
   * The feature id for the '<em><b>Owned Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HETE_STATEMENT_CS__OWNED_CONDITIONS = 0;

  /**
   * The number of structural features of the '<em>Hete Statement CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HETE_STATEMENT_CS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.ncl.nCL.impl.HeteConditionCSImpl <em>Hete Condition CS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.ncl.nCL.impl.HeteConditionCSImpl
   * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHeteConditionCS()
   * @generated
   */
  int HETE_CONDITION_CS = 7;

  /**
   * The feature id for the '<em><b>Owned Element A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HETE_CONDITION_CS__OWNED_ELEMENT_A = 0;

  /**
   * The feature id for the '<em><b>Owned Element B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HETE_CONDITION_CS__OWNED_ELEMENT_B = 1;

  /**
   * The feature id for the '<em><b>Owned Element</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HETE_CONDITION_CS__OWNED_ELEMENT = 2;

  /**
   * The number of structural features of the '<em>Hete Condition CS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HETE_CONDITION_CS_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.ncl.nCL.TopLevelCP <em>Top Level CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Top Level CP</em>'.
   * @see org.xtext.example.ncl.nCL.TopLevelCP
   * @generated
   */
  EClass getTopLevelCP();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ncl.nCL.TopLevelCP#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.ncl.nCL.TopLevelCP#getName()
   * @see #getTopLevelCP()
   * @generated
   */
  EAttribute getTopLevelCP_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ncl.nCL.TopLevelCP#getOwnedImports <em>Owned Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Imports</em>'.
   * @see org.xtext.example.ncl.nCL.TopLevelCP#getOwnedImports()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedImports();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ncl.nCL.TopLevelCP#getOwnedHomocoms <em>Owned Homocoms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Homocoms</em>'.
   * @see org.xtext.example.ncl.nCL.TopLevelCP#getOwnedHomocoms()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedHomocoms();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ncl.nCL.TopLevelCP#getOwnedHetecoms <em>Owned Hetecoms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Hetecoms</em>'.
   * @see org.xtext.example.ncl.nCL.TopLevelCP#getOwnedHetecoms()
   * @see #getTopLevelCP()
   * @generated
   */
  EReference getTopLevelCP_OwnedHetecoms();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ncl.nCL.HomocomCP <em>Homocom CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Homocom CP</em>'.
   * @see org.xtext.example.ncl.nCL.HomocomCP
   * @generated
   */
  EClass getHomocomCP();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ncl.nCL.HomocomCP#getOwnedMetaModels <em>Owned Meta Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Meta Models</em>'.
   * @see org.xtext.example.ncl.nCL.HomocomCP#getOwnedMetaModels()
   * @see #getHomocomCP()
   * @generated
   */
  EReference getHomocomCP_OwnedMetaModels();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ncl.nCL.HomocomCP#getOwnedStatements <em>Owned Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Statements</em>'.
   * @see org.xtext.example.ncl.nCL.HomocomCP#getOwnedStatements()
   * @see #getHomocomCP()
   * @generated
   */
  EReference getHomocomCP_OwnedStatements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ncl.nCL.metaModelTypeCS <em>meta Model Type CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>meta Model Type CS</em>'.
   * @see org.xtext.example.ncl.nCL.metaModelTypeCS
   * @generated
   */
  EClass getmetaModelTypeCS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ncl.nCL.metaModelTypeCS#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.ncl.nCL.metaModelTypeCS#getName()
   * @see #getmetaModelTypeCS()
   * @generated
   */
  EAttribute getmetaModelTypeCS_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ncl.nCL.HomoStatementCS <em>Homo Statement CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Homo Statement CS</em>'.
   * @see org.xtext.example.ncl.nCL.HomoStatementCS
   * @generated
   */
  EClass getHomoStatementCS();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ncl.nCL.HomoStatementCS#getOwnedConditions <em>Owned Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Conditions</em>'.
   * @see org.xtext.example.ncl.nCL.HomoStatementCS#getOwnedConditions()
   * @see #getHomoStatementCS()
   * @generated
   */
  EReference getHomoStatementCS_OwnedConditions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ncl.nCL.HomoConditionCS <em>Homo Condition CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Homo Condition CS</em>'.
   * @see org.xtext.example.ncl.nCL.HomoConditionCS
   * @generated
   */
  EClass getHomoConditionCS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ncl.nCL.HomoConditionCS#getOwnedElementA <em>Owned Element A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owned Element A</em>'.
   * @see org.xtext.example.ncl.nCL.HomoConditionCS#getOwnedElementA()
   * @see #getHomoConditionCS()
   * @generated
   */
  EAttribute getHomoConditionCS_OwnedElementA();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ncl.nCL.HomoConditionCS#getOwnedElementB <em>Owned Element B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owned Element B</em>'.
   * @see org.xtext.example.ncl.nCL.HomoConditionCS#getOwnedElementB()
   * @see #getHomoConditionCS()
   * @generated
   */
  EAttribute getHomoConditionCS_OwnedElementB();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.ncl.nCL.HomoConditionCS#getOwnedElement <em>Owned Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Owned Element</em>'.
   * @see org.xtext.example.ncl.nCL.HomoConditionCS#getOwnedElement()
   * @see #getHomoConditionCS()
   * @generated
   */
  EAttribute getHomoConditionCS_OwnedElement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ncl.nCL.HetecomCP <em>Hetecom CP</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hetecom CP</em>'.
   * @see org.xtext.example.ncl.nCL.HetecomCP
   * @generated
   */
  EClass getHetecomCP();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ncl.nCL.HetecomCP#getOwnedModels <em>Owned Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Models</em>'.
   * @see org.xtext.example.ncl.nCL.HetecomCP#getOwnedModels()
   * @see #getHetecomCP()
   * @generated
   */
  EReference getHetecomCP_OwnedModels();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ncl.nCL.HetecomCP#getOwnedStatements <em>Owned Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Statements</em>'.
   * @see org.xtext.example.ncl.nCL.HetecomCP#getOwnedStatements()
   * @see #getHetecomCP()
   * @generated
   */
  EReference getHetecomCP_OwnedStatements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ncl.nCL.HeteStatementCS <em>Hete Statement CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hete Statement CS</em>'.
   * @see org.xtext.example.ncl.nCL.HeteStatementCS
   * @generated
   */
  EClass getHeteStatementCS();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.ncl.nCL.HeteStatementCS#getOwnedConditions <em>Owned Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Owned Conditions</em>'.
   * @see org.xtext.example.ncl.nCL.HeteStatementCS#getOwnedConditions()
   * @see #getHeteStatementCS()
   * @generated
   */
  EReference getHeteStatementCS_OwnedConditions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.ncl.nCL.HeteConditionCS <em>Hete Condition CS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hete Condition CS</em>'.
   * @see org.xtext.example.ncl.nCL.HeteConditionCS
   * @generated
   */
  EClass getHeteConditionCS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ncl.nCL.HeteConditionCS#getOwnedElementA <em>Owned Element A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owned Element A</em>'.
   * @see org.xtext.example.ncl.nCL.HeteConditionCS#getOwnedElementA()
   * @see #getHeteConditionCS()
   * @generated
   */
  EAttribute getHeteConditionCS_OwnedElementA();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.ncl.nCL.HeteConditionCS#getOwnedElementB <em>Owned Element B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Owned Element B</em>'.
   * @see org.xtext.example.ncl.nCL.HeteConditionCS#getOwnedElementB()
   * @see #getHeteConditionCS()
   * @generated
   */
  EAttribute getHeteConditionCS_OwnedElementB();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.ncl.nCL.HeteConditionCS#getOwnedElement <em>Owned Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Owned Element</em>'.
   * @see org.xtext.example.ncl.nCL.HeteConditionCS#getOwnedElement()
   * @see #getHeteConditionCS()
   * @generated
   */
  EAttribute getHeteConditionCS_OwnedElement();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  NCLFactory getNCLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.ncl.nCL.impl.TopLevelCPImpl <em>Top Level CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ncl.nCL.impl.TopLevelCPImpl
     * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getTopLevelCP()
     * @generated
     */
    EClass TOP_LEVEL_CP = eINSTANCE.getTopLevelCP();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOP_LEVEL_CP__NAME = eINSTANCE.getTopLevelCP_Name();

    /**
     * The meta object literal for the '<em><b>Owned Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_IMPORTS = eINSTANCE.getTopLevelCP_OwnedImports();

    /**
     * The meta object literal for the '<em><b>Owned Homocoms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_HOMOCOMS = eINSTANCE.getTopLevelCP_OwnedHomocoms();

    /**
     * The meta object literal for the '<em><b>Owned Hetecoms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TOP_LEVEL_CP__OWNED_HETECOMS = eINSTANCE.getTopLevelCP_OwnedHetecoms();

    /**
     * The meta object literal for the '{@link org.xtext.example.ncl.nCL.impl.HomocomCPImpl <em>Homocom CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ncl.nCL.impl.HomocomCPImpl
     * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHomocomCP()
     * @generated
     */
    EClass HOMOCOM_CP = eINSTANCE.getHomocomCP();

    /**
     * The meta object literal for the '<em><b>Owned Meta Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOMOCOM_CP__OWNED_META_MODELS = eINSTANCE.getHomocomCP_OwnedMetaModels();

    /**
     * The meta object literal for the '<em><b>Owned Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOMOCOM_CP__OWNED_STATEMENTS = eINSTANCE.getHomocomCP_OwnedStatements();

    /**
     * The meta object literal for the '{@link org.xtext.example.ncl.nCL.impl.metaModelTypeCSImpl <em>meta Model Type CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ncl.nCL.impl.metaModelTypeCSImpl
     * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getmetaModelTypeCS()
     * @generated
     */
    EClass META_MODEL_TYPE_CS = eINSTANCE.getmetaModelTypeCS();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute META_MODEL_TYPE_CS__NAME = eINSTANCE.getmetaModelTypeCS_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.ncl.nCL.impl.HomoStatementCSImpl <em>Homo Statement CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ncl.nCL.impl.HomoStatementCSImpl
     * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHomoStatementCS()
     * @generated
     */
    EClass HOMO_STATEMENT_CS = eINSTANCE.getHomoStatementCS();

    /**
     * The meta object literal for the '<em><b>Owned Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HOMO_STATEMENT_CS__OWNED_CONDITIONS = eINSTANCE.getHomoStatementCS_OwnedConditions();

    /**
     * The meta object literal for the '{@link org.xtext.example.ncl.nCL.impl.HomoConditionCSImpl <em>Homo Condition CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ncl.nCL.impl.HomoConditionCSImpl
     * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHomoConditionCS()
     * @generated
     */
    EClass HOMO_CONDITION_CS = eINSTANCE.getHomoConditionCS();

    /**
     * The meta object literal for the '<em><b>Owned Element A</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOMO_CONDITION_CS__OWNED_ELEMENT_A = eINSTANCE.getHomoConditionCS_OwnedElementA();

    /**
     * The meta object literal for the '<em><b>Owned Element B</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOMO_CONDITION_CS__OWNED_ELEMENT_B = eINSTANCE.getHomoConditionCS_OwnedElementB();

    /**
     * The meta object literal for the '<em><b>Owned Element</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOMO_CONDITION_CS__OWNED_ELEMENT = eINSTANCE.getHomoConditionCS_OwnedElement();

    /**
     * The meta object literal for the '{@link org.xtext.example.ncl.nCL.impl.HetecomCPImpl <em>Hetecom CP</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ncl.nCL.impl.HetecomCPImpl
     * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHetecomCP()
     * @generated
     */
    EClass HETECOM_CP = eINSTANCE.getHetecomCP();

    /**
     * The meta object literal for the '<em><b>Owned Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HETECOM_CP__OWNED_MODELS = eINSTANCE.getHetecomCP_OwnedModels();

    /**
     * The meta object literal for the '<em><b>Owned Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HETECOM_CP__OWNED_STATEMENTS = eINSTANCE.getHetecomCP_OwnedStatements();

    /**
     * The meta object literal for the '{@link org.xtext.example.ncl.nCL.impl.HeteStatementCSImpl <em>Hete Statement CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ncl.nCL.impl.HeteStatementCSImpl
     * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHeteStatementCS()
     * @generated
     */
    EClass HETE_STATEMENT_CS = eINSTANCE.getHeteStatementCS();

    /**
     * The meta object literal for the '<em><b>Owned Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HETE_STATEMENT_CS__OWNED_CONDITIONS = eINSTANCE.getHeteStatementCS_OwnedConditions();

    /**
     * The meta object literal for the '{@link org.xtext.example.ncl.nCL.impl.HeteConditionCSImpl <em>Hete Condition CS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.ncl.nCL.impl.HeteConditionCSImpl
     * @see org.xtext.example.ncl.nCL.impl.NCLPackageImpl#getHeteConditionCS()
     * @generated
     */
    EClass HETE_CONDITION_CS = eINSTANCE.getHeteConditionCS();

    /**
     * The meta object literal for the '<em><b>Owned Element A</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HETE_CONDITION_CS__OWNED_ELEMENT_A = eINSTANCE.getHeteConditionCS_OwnedElementA();

    /**
     * The meta object literal for the '<em><b>Owned Element B</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HETE_CONDITION_CS__OWNED_ELEMENT_B = eINSTANCE.getHeteConditionCS_OwnedElementB();

    /**
     * The meta object literal for the '<em><b>Owned Element</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HETE_CONDITION_CS__OWNED_ELEMENT = eINSTANCE.getHeteConditionCS_OwnedElement();

  }

} //NCLPackage
