/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.ncl.nCL;

import org.eclipse.emf.common.util.EList;

//import org.eclipse.emf.ecore.EObject;

import org.eclipse.ocl.xtext.basecs.ImportCS;
import org.eclipse.ocl.xtext.completeoclcs.CompleteOCLDocumentCS;

import org.eclipse.ocl.xtext.completeoclcs.ContextDeclCS;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Top Level CP</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.ncl.nCL.TopLevelCP#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.ncl.nCL.TopLevelCP#getOwnedImports <em>Owned Imports</em>}</li>
 *   <li>{@link org.xtext.example.ncl.nCL.TopLevelCP#getOwnedHomocoms <em>Owned Homocoms</em>}</li>
 *   <li>{@link org.xtext.example.ncl.nCL.TopLevelCP#getOwnedHetecoms <em>Owned Hetecoms</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.ncl.nCL.NCLPackage#getTopLevelCP()
 * @model
 * @generated
 */
public interface TopLevelCP extends CompleteOCLDocumentCS
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.ncl.nCL.NCLPackage#getTopLevelCP_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.ncl.nCL.TopLevelCP#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Owned Imports</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.ocl.xtext.basecs.ImportCS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Imports</em>' containment reference list.
   * @see org.xtext.example.ncl.nCL.NCLPackage#getTopLevelCP_OwnedImports()
   * @model containment="true"
   * @generated
   */
  EList<ImportCS> getOwnedImports();

  /**
   * Returns the value of the '<em><b>Owned Homocoms</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ncl.nCL.HomocomCP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Homocoms</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Homocoms</em>' containment reference list.
   * @see org.xtext.example.ncl.nCL.NCLPackage#getTopLevelCP_OwnedHomocoms()
   * @model containment="true"
   * @generated
   */
  EList<HomocomCP> getOwnedHomocoms();

  /**
   * Returns the value of the '<em><b>Owned Hetecoms</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.ncl.nCL.HetecomCP}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Owned Hetecoms</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Owned Hetecoms</em>' containment reference list.
   * @see org.xtext.example.ncl.nCL.NCLPackage#getTopLevelCP_OwnedHetecoms()
   * @model containment="true"
   * @generated
   */
  EList<HetecomCP> getOwnedHetecoms();

} // TopLevelCP
